trigger:
  - main

name: 'Run Playwright'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Testing'
    jobs:
      - job: 'Run_Playwright_Test'
        displayName: 'Install and Run playwright'

        steps:
          - task: NodeTool@0
            inputs: 
              versionSpec: '20.x'
            displayName: 'Install Node JS'

          - script: npm install
            displayName: 'Install Dependencies'

          - script: npx playwright install
            displayName: 'Install Playwright browsers'

          - script: npx playwright test --output=playwright-report
            displayName: 'Run Playwright Test'    

          - task: PublishBuildArtifacts@1
            inputs:
              PathToPublish: 'playwright-report'
              ArtifactName: 'TestResults'
              publishLocation: 'Container'
            displayName: 'Publish Test Artifacts'

          - script: |
              echo "Cloning dashboard repo..."
              git config --global user.email "automation@example.com"
              git config --global user.name "CI Bot"
              git clone https://${PAT_Token}@dev.azure.com/YOUR_ORG/YOUR_PROJECT/_git/TestResultsDashboard

              echo "Copying test report..."
              rm -rf TestResultsDashboard/reports/playwright-report
              mkdir -p TestResultsDashboard/reports/playwright-report
              cp -r playwright-report/* TestResultsDashboard/reports/playwright-report/

              cd TestResultsDashboard
              git add .
              git commit -m "Update Playwright report from $(Build.BuildNumber)"
              git push
            displayName: 'Push test report to dashboard repo'
