trigger:
  - main

name: 'Run Playwright'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Testing'
    jobs:
      - job: 'Run_Playwright_Test'
        displayName: 'Install and Run playwright'

        steps:
          - task: NodeTool@0
            inputs: 
              versionSpec: '20.x'
            displayName: 'Install Node JS'

          - script: npm install
            displayName: 'Install Dependencies'

          - script: npx playwright install
            displayName: 'Install Playwright browsers'

          - script: npx playwright test --output=playwright-report
            displayName: 'Run Playwright Test'    

          - task: PublishBuildArtifacts@1
            inputs:
              PathToPublish: 'playwright-report'
              ArtifactName: 'TestResults'
              publishLocation: 'Container'
            displayName: 'Publish Test Artifacts'
    